---
- name: Ensure volume for grafana data exists
  docker_volume:
    name: "{{ grafana_data_volume }}"
    state: present

- name: Create grafana container
  docker_container:
    name: "{{ grafana_container_name }}"
    image: "{{ grafana_image_name }}"
    state: started
    restart_policy: always
    env:
      GF_SERVER_ROOT_URL: "https://{{ grafana_domain_name }}"
      GF_SECURITY_ADMIN_PASSWORD: "{{ grafana_admin_password }}"
    volumes:
      - "{{ grafana_data_volume }}:/var/lib/grafana"
    labels:
      traefik.enable: "true"
      traefik.http.routers.grafana.rule: "Host(`{{ grafana_domain_name }}`)"
      traefik.http.routers.grafana.tls: "true"
      traefik.http.routers.grafana.tls.certresolver: "letsencrypt"
