---
dependency:
  name: galaxy
driver:
  name: lxd
lint:
  name: yamllint
platforms:
  - name: molecule-prometheus
    source:
      type: image
      mode: pull
      alias: debian/buster/amd64
    config:
      security.nesting: 'true'
provisioner:
  name: ansible
  lint:
    name: ansible-lint
verifier:
  name: testinfra
  lint:
    name: flake8
